#!/usr/bin/env node

// initalize core
var resolve = require('path').resolve.bind(null, __dirname)
  , glagol  = require('glagol')
  , server  = glagol(resolve('server'))
  , tasks   = glagol(resolve('tasks'),
                { formats: { null: server().task.parse } });

// start, or export
module.exports = { server: server, tasks: tasks };
if (module === require.main) server().main(tasks);
