#!/usr/bin/env node

// initalize core
var glagol = require('glagol')
  , app    = glagol(require('path').resolve(__dirname, 'server'), {})

// set correct glagol options on symlinked directories
var libs = ['lib/bundler', 'lib/server'];
libs.map(function (lib) {
  var lib = app.get(lib);
  lib.options = lib.get('glagol-options.js')();
})

// start, or export
module.exports = app;
if (module === require.main) {
  app().main();
  if (process.versions.electron) {
    console.log('starting electron...')
    var electron = require('electron')
      , w;
    electron.app.on('ready', function () {
      w = new (require('electron').BrowserWindow)({ frame: false })
      w.loadURL('http://localhost:1617');
      console.log("---->", w)
      w.on('closed', function () { w = null })
    })
  }
}
